---
hostname: panopoly-kit.dev
ntp_timezone: America/Chicago

apache_vhosts:
  - { servername: 'panopoly-kit.dev', documentroot: '/var/www/panopoly-kit' }

# MySQL
mysql_root_password: root
mysql_key_buffer_size: "16M"
mysql_max_allowed_packet: "64M"
mysql_table_open_cache: "256"
mysql_sort_buffer_size: "1M"
mysql_read_buffer_size: "1M"
mysql_read_rnd_buffer_size: "2M"
mysql_myisam_sort_buffer_size: "16M"
mysql_thread_cache_size: "25"
mysql_query_cache_size: "16M"
mysql_innodb_buffer_pool_size: "64M"
mysql_innodb_log_file_size: "8M"
mysql_innodb_log_buffer_size: "4M"
mysql_innodb_flush_log_at_trx_commit: "2"

mysql_databases:
  - { name: panopoly }
mysql_users:
  - { name: panopoly, password: "panopoly", priv: "panopoly.*:ALL" }

#PHP
php_memory_limit: "256M"
php_max_execution_time: "240"
php_apc_enabled_in_ini: true
php_apc_stat: "0"

#Composer
composer_global_packages: []
