---
- name: Clean up apt.
  command: "{{ item }}"
  with_items:
    - apt-get -y autoremove
    - apt-get -y clean

- name: Update system
  apt: upgrade=yes update_cache=yes

- name: Copy panopoly-kit command
  copy: src=../../../files/panopoly-kit dest=/usr/local/bin/panopoly-kit mode=0755

- name: Make /var/www writable by www-data
  file: path=/var/www owner=root group=www-data mode="g+aS"

- name: Add our user to the www-data group
  user: name={{kit_user}} groups=www-data append=yes
