---
- name: Clean up apt.
  command: "{{ item }}"
  with_items:
    - apt-get -y autoremove
    - apt-get -y clean

- name: Update system
  apt: upgrade=yes update_cache=yes

- name: Copy panopoly-kit command
  copy: src=../../../files/panopoly-kit dest=/usr/local/bin/panopoly-kit mode=0755

- name: Make /var/www writable by www-data
  file: path=/var/www owner=root group=www-data mode="g+rws"

- name: Add our user to the www-data group
  user: name={{kit_user}} groups=www-data append=yes

- name: Install Java (for Selenium and PHPStorm)
  apt:
    name: openjdk-7-jdk
    state: installed

 # @todo: geerlingguy.php should install this, but doesn't for some reason. We
 # should figure out why and fix it! For now, force it again...
- name: Install PHP gd extension
  apt:
    name: php5-gd
    state: installed

- name: Ensure /usr/local/share/panopoly-kit directory
  file: path=/usr/local/share/panopoly-kit state=directory owner=root group=root

- name: Create PHPStorm project file
  copy: src=../../../files/phpstorm-project.tar.gz dest=/usr/local/share/panopoly-kit/phpstorm-project.tar.gz owner=root group=root mode=0755
