---
- include: virtualbox.yml
- include: cleanup.yml

- name: Install ubuntu-dektop
  apt: name=ubuntu-desktop state=installed

- name: Assure conf.d directory for LightDM
  file: path=/etc/lightdm/lightdm.conf.d/ state=directory

- name: Update LightDM
  template: src=lightdm.conf dest=/etc/lightdm/lightdm.conf.d/50-panopoly-kit.conf
