- name: Install ubuntu-dektop
  apt: name=ubuntu-desktop state=installed

#- name: Provision GDM configuration
#  template: src=gdm_custom.conf dest=/etc/gdm/custom.conf

- name: Assure conf.d directory for LightDM
  file: path=/etc/lightdm/lightdm.conf.d/ state=directory

- name: Update LightDM
  template: src=lightdm.conf dest=/etc/lightdm/lightdm.conf.d/50-panopoly-kit.conf

# Cleanup tasks.
- name: Remove unneeded packages.
  apt: "pkg={{ item }} state=absent"
  with_items:
    - ppp
    - pppconfig
    - pppoeconf
    - cpp
    - gcc
    - g++
    - libx11-data
    - xauth
    - libxmuu1
    - libxcb1
    - libx11-6
    - libxext6
    - linux-source

- name: Remove uneeded packages (by regex).
  shell: "apt-get -y remove '.*-dev$'"

- name: Clean up apt.
  command: "{{ item }}"
  with_items:
    - apt-get -y autoremove
    - apt-get -y clean
