---
# Run initial clean up of the machine before installing the UI et all.
- include: cleanup.yml

# Set up GuestAdditions and DKMS.
- include: virtualbox.yml

# Install Ubuntu Desktop!
- name: Install ubuntu-dektop
  apt: name=ubuntu-desktop state=installed

- name: Ensure conf.d directory for LightDM
  file: path=/etc/lightdm/lightdm.conf.d/ state=directory

- name: Update LightDM
  template: src=lightdm.conf dest=/etc/lightdm/lightdm.conf.d/50-panopoly-kit.conf

- name: Remove unneeded desktop recommended items
  apt: "pkg={{ item }} state=absent"
  with_items:
    - brasero
    - cheese
    - empathy
    - gnome-sudoku
    - gnomine
    - libreoffice-calc
    - libreoffice-gnome
    - libreoffice-impress
    - libreoffice-math
    - libreoffice-ogltrans
    - libreoffice-pdfimport
    - libreoffice-presentation-minimizer
    - libreoffice-style-human
    - libreoffice-writer
    - shotwell
    - simple-scan
    - thunderbird
    - thunderbird-gnome-support

- name: Ensure user bin directory
  file: path=/home/{{ kit_ui_user }}/bin state=directory owner={{ kit_ui_user }} group={{ kit_ui_user }}

- name: Ensure user desktop directory
  file: path=/home/{{ kit_ui_user }}/Desktop state=directory owner={{ kit_ui_user }} group={{ kit_ui_user }}

- name: Create desktop shortcut to terminal
  copy: src=terminal.desktop dest=/home/{{ kit_ui_user }}/Desktop/Terminal.desktop owner={{ kit_ui_user }} group={{ kit_ui_user }} mode=0755

- name: Create desktop shortcut to panopoly-kit
  copy: src=panopoly-kit.desktop dest=/home/{{ kit_ui_user }}/Desktop/Panopoly-Kit.desktop owner={{ kit_ui_user }} group={{ kit_ui_user }} mode=0755
