---
- name: Install DKMS
  apt: pkg=dkms state=installed

- name: Get VirtualBox version.
  shell: cat /home/{{ kit_ui_user }}/.vbox_version
  register: virtualbox_version

- name: Mount VirtualBox guest additions ISO.
  mount: >
    name=/tmp/vbox
    src=/home/{{ kit_ui_user }}/VBoxGuestAdditions_{{ virtualbox_version.stdout }}.iso
    opts=loop
    state=mounted
    fstype=iso9660

- name: Run VirtualBox guest additions installation.
  shell: sh /tmp/vbox/VBoxLinuxAdditions.run
  failed_when: false

- name: Unmount VirtualBox guest additions ISO.
  mount: >
    name=/tmp/vbox
    src=/home/{{ kit_ui_user }}/VBoxGuestAdditions_{{ virtualbox_version.stdout }}.iso
    state=unmounted
    fstype=iso9660

- name: Install VirtualBox Guest DKMS
  apt: pkg=virtualbox-guest-dkms state=installed
