---
- hosts: panopoly
  gather_facts: yes
  sudo: yes

  vars:
    - hostname: panopoly-kit.dev
    - ntp_timezone: America/Chicago
    - mysql_root_password: root
    - mysql_databases:
        - { name: panopoly }
    - apache_vhosts:
        - { servername: 'panopoly-kit.dev', documentroot: '/var/www/panopoly-kit' }

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600

    - apt: "name={{ item }} state=installed"
      with_items:
        - git
        - wget
        - curl
        - vim

  roles:
    - geerlingguy.packer-debian
    - geerlingguy.ntp
    - geerlingguy.mysql
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.composer
    - geerlingguy.drush

  tasks:
    - name: Copy panopoly-kit command
      copy: src=files/panopoly-kit dest=/usr/local/bin/panopoly-kit mode=0755
