---
- hosts: panopoly
  gather_facts: yes
  sudo: yes

  vars_files:
    - config/main.yml

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600

    - name: Install git, wget, curl, vim
      apt: "name={{ item }} state=installed"
      with_items:
        - git
        - wget
        - curl
        - vim

  roles:
    - geerlingguy.git
    - geerlingguy.ntp
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.composer
    - geerlingguy.drush
    # kit-ui ismaking the mysql role go crazy with notify.
    - panopoly.kit-ui
    - panopoly.kit
    - geerlingguy.mysql
    - geerlingguy.php-mysql
